# Site settings
title: ProductJam!
subtitle: Occasional improvised chat for people that build products.

# Build settings
markdown: kramdown
exclude: [vendor, Gemfile, Gemfile.lock, README.md, CNAME]
